package:
  name: bufr_stuff
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.1.0') }}

source:
  path: .

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: 'intel_test'

requirements:
  build:
        - intelpython
        - jpeg 8d
        - libpng
        - libssh2
        - curl
        - icc_rt ==16.0.3 intel_5
        - impi_rt ==2017.0.1 intel_1
        - hdf5 ==1.8.19 intel_test
        - netcdf-fortran 4.4.4 intel_test
        - netcdf 4.4.1.1 intel_test
        - gsi ==3.5 intel_test
  run:

about:
    home:
